<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SelectOption extends Seeder
{
    public function run()
    {
        $select_data = [
            ['number' => '1', 'param' => 'depreciation', 'name' => 'straight line',],
            ['number' => '2', 'param' => 'depreciation', 'name' => 'declining balance',],
            ['number' => '1', 'param' => 'category account', 'name' => '1-asset',],
            ['number' => '2', 'param' => 'category account', 'name' => '2-liability',],
            ['number' => '3', 'param' => 'category account', 'name' => '3-equity',],
            ['number' => '4', 'param' => 'category account', 'name' => '4-income',],
            ['number' => '5', 'param' => 'category account', 'name' => '5-hpp',],
            ['number' => '6', 'param' => 'category account', 'name' => '6-expense',],
            ['number' => '7', 'param' => 'category account', 'name' => '7-income2',],
            ['number' => '8', 'param' => 'category account', 'name' => '8-expense2',],
            ['number' => '1', 'param' => 'blood', 'name' => 'A',],
            ['number' => '2', 'param' => 'blood', 'name' => 'B',],
            ['number' => '3', 'param' => 'blood', 'name' => 'AB',],
            ['number' => '4', 'param' => 'blood', 'name' => 'O',],
            ['number' => '1', 'param' => 'diploma', 'name' => 'SD',],
            ['number' => '2', 'param' => 'diploma', 'name' => 'SMP',],
            ['number' => '3', 'param' => 'diploma', 'name' => 'SMU',],
            ['number' => '4', 'param' => 'diploma', 'name' => 'D3',],
            ['number' => '5', 'param' => 'diploma', 'name' => 'S1',],
            ['number' => '6', 'param' => 'diploma', 'name' => 'S2',],
            ['number' => '1', 'param' => 'diploma st', 'name' => 'hold',],
            ['number' => '2', 'param' => 'diploma st', 'name' => 'returned',],
            ['number' => '1', 'param' => 'employee st', 'group' => 'Perjanjian Kerja Waktu Tertentu', 'name' => 'PKWT',],
            ['number' => '2', 'param' => 'employee st', 'group' => 'Perjanjian Kerja Waktu Tidak Tertentu', 'name' => 'PKWTT',],
            ['number' => '3', 'param' => 'employee st', 'group' => 'Pegawai Harian Lepas', 'name' => 'PHL',],


            ['number' => '1', 'param' => 'out mode', 'name' => 'resign',],
            ['number' => '2', 'param' => 'out mode', 'name' => 'layoffs',],
            ['number' => '3', 'param' => 'out mode', 'name' => 'dismissal',],
            ['number' => '4', 'param' => 'out mode', 'name' => 'retired',],
            ['number' => '1', 'param' => 'object', 'name' => 'project',],
            ['number' => '2', 'param' => 'object', 'name' => 'branch',],
            ['number' => '3', 'param' => 'object', 'name' => 'equipment tool',],
            ['number' => '4', 'param' => 'object', 'name' => 'land building',],
            ['number' => '11', 'param' => 'object', 'name' => 'employee',],
            ['number' => '12', 'param' => 'object', 'name' => 'other',],
            ['number' => '1', 'param' => 'selopt', 'group' => 'main', 'name' => 'region',],
            ['number' => '2', 'param' => 'selopt', 'group' => 'main', 'name' => 'division',],
            ['number' => '3', 'param' => 'selopt', 'group' => 'hrd', 'name' => 'position',],
            ['number' => '4', 'param' => 'selopt', 'group' => 'hrd', 'name' => 'class',],
            ['number' => '5', 'param' => 'selopt', 'group' => 'hrd', 'name' => 'salary group',],

            // ['number' => '1', 'param' => 'itemso', 'name' => 'item',],
            // ['number' => '2', 'param' => 'itemso', 'name' => 'alat tool',],
            // ['number' => '3', 'param' => 'itemso', 'name' => 'tanah bangunan',],
            // ['number' => '4', 'param' => 'itemso', 'name' => 'inventaris',],
            ['number' => '1', 'param' => 'numbering', 'group' => 'budget', 'name' => 'project budget',],
            ['number' => '2', 'param' => 'numbering', 'group' => 'budget', 'name' => 'account budget',],
            ['number' => '3', 'param' => 'numbering', 'group' => 'purchase', 'name' => 'request item',],
            ['number' => '4', 'param' => 'numbering', 'group' => 'purchase', 'name' => 'take item',],
            ['number' => '5', 'param' => 'numbering', 'group' => 'purchase', 'name' => 'keluar gudang',],
            ['number' => '6', 'param' => 'numbering', 'group' => 'purchase', 'name' => 'pesan barang',],
            ['number' => '7', 'param' => 'numbering', 'group' => 'cash', 'name' => 'direct cash',],
            ['number' => '8', 'param' => 'numbering', 'group' => 'cash', 'name' => 'indirect cash',],
            ['number' => '9', 'param' => 'numbering', 'group' => 'cash', 'name' => 'advance payment',],
            ['number' => '10', 'param' => 'numbering', 'group' => 'cash', 'name' => 'road money',],
            ['number' => '11', 'param' => 'numbering', 'group' => 'cash', 'name' => 'cash transfer',],
            ['number' => '12', 'param' => 'numbering', 'group' => 'sales', 'name' => 'pesan jual',],
            ['number' => '13', 'param' => 'numbering', 'group' => 'sales', 'name' => 'pesan sewa',],
            ['number' => '14', 'param' => 'numbering', 'group' => 'leave', 'name' => 'leave',],

            ['number' => '1', 'param' => 'group account', 'group' => 'asset', 'name' => 'equipment tool',],
            ['number' => '2', 'param' => 'group account', 'group' => 'asset', 'name' => 'land building',],
            ['number' => '3', 'param' => 'group account', 'group' => 'asset', 'name' => 'inventory',],
            ['number' => '4', 'param' => 'group account', 'group' => 'stock', 'name' => 'item',],
            ['number' => '5', 'param' => 'group account', 'group' => 'stock', 'name' => 'material',],
            ['number' => '6', 'param' => 'group account', 'group' => 'person', 'name' => 'employee',],
            ['number' => '7', 'param' => 'group account', 'group' => 'person', 'name' => 'customer',],
            ['number' => '8', 'param' => 'group account', 'group' => 'person', 'name' => 'supplier',],
            ['number' => '9', 'param' => 'group account', 'group' => 'person', 'name' => 'subcontractor',],
            ['number' => '1', 'param' => 'tax account', 'group' => 'tax', 'name' => 'vat',],
            ['number' => '2', 'param' => 'tax account', 'group' => 'tax', 'name' => 'income tax',],
            ['number' => '3', 'param' => 'tax account', 'group' => 'tax', 'name' => 'other tax',],
            ['number' => '1', 'param' => 'cash account', 'group' => 'cash', 'name' => 'cash',],
            ['number' => '2', 'param' => 'cash account', 'group' => 'cash', 'name' => 'bank',],
            ['number' => '1', 'param' => 'sim', 'group' => 'SIM A', 'name' => 'SIM A',],
            ['number' => '2', 'param' => 'sim', 'group' => 'SIM A', 'name' => 'SIM A Umum',],
            ['number' => '3', 'param' => 'sim', 'group' => 'SIM B', 'name' => 'SIM BI',],
            ['number' => '4', 'param' => 'sim', 'group' => 'SIM B', 'name' => 'SIM BI Umum',],
            ['number' => '5', 'param' => 'sim', 'group' => 'SIM B', 'name' => 'SIM BII',],
            ['number' => '6', 'param' => 'sim', 'group' => 'SIM B', 'name' => 'SIM BII Umum',],
            ['number' => '7', 'param' => 'sim', 'group' => 'SIM C', 'name' => 'SIM C',],
            ['number' => '8', 'param' => 'sim', 'group' => 'SIM C', 'name' => 'SIM CI Umum',],
            ['number' => '9', 'param' => 'sim', 'group' => 'SIM C', 'name' => 'SIM CII',],
            ['number' => '10', 'param' => 'sim', 'group' => 'SIM D', 'name' => 'SIM D',],
            ['number' => '11', 'param' => 'sim', 'group' => 'SIM D', 'name' => 'SIM DI',],
            ['number' => '1', 'param' => 'ptkp', 'group' => 'TK', 'name' => 'TK/0',],
            ['number' => '2', 'param' => 'ptkp', 'group' => 'TK', 'name' => 'TK/1',],
            ['number' => '3', 'param' => 'ptkp', 'group' => 'TK', 'name' => 'TK/2',],
            ['number' => '4', 'param' => 'ptkp', 'group' => 'TK', 'name' => 'TK/3',],
            ['number' => '5', 'param' => 'ptkp', 'group' => 'K', 'name' => 'K/0',],
            ['number' => '6', 'param' => 'ptkp', 'group' => 'K', 'name' => 'K/1',],
            ['number' => '7', 'param' => 'ptkp', 'group' => 'K', 'name' => 'K/2',],
            ['number' => '8', 'param' => 'ptkp', 'group' => 'K', 'name' => 'K/3',],
            ['number' => '9', 'param' => 'ptkp', 'group' => 'K/I', 'name' => 'K/I/0',],
            ['number' => '10', 'param' => 'ptkp', 'group' => 'K/I', 'name' => 'K/I/1',],
            ['number' => '11', 'param' => 'ptkp', 'group' => 'K/I', 'name' => 'K/I/2',],
            ['number' => '12', 'param' => 'ptkp', 'group' => 'K/I', 'name' => 'K/I/3',],
            ['number' => '1', 'param' => 'konfigurasi', 'name' => 'jlsetuju',],
            ['number' => '2', 'param' => 'konfigurasi', 'name' => 'cariharga',],
            ['number' => '1', 'param' => 'group industry', 'name' => 'industry',],
            ['number' => '2', 'param' => 'group industry', 'name' => 'non industry',],
            ['number' => '3', 'param' => 'group industry', 'name' => 'subcontractor',],
            ['number' => '1', 'param' => 'trip', 'name' => 'bbm',],
            ['number' => '2', 'param' => 'trip', 'name' => 'honor',],
            ['number' => '3', 'param' => 'trip', 'name' => 'byantri',],
            ['number' => '4', 'param' => 'trip', 'name' => 'lembur biasa',],
            ['number' => '5', 'param' => 'trip', 'name' => 'lembur besar',],
            ['number' => '6', 'param' => 'trip', 'name' => 'uang makan',],
            ['number' => '1', 'param' => 'tool shape', 'name' => 'heavy equipment',],
            ['number' => '2', 'param' => 'tool shape', 'name' => 'industrial tool',],
            ['number' => '3', 'param' => 'tool shape', 'name' => 'truck',],
            ['number' => '4', 'param' => 'tool shape', 'name' => 'vehicle',],
            ['number' => '1', 'param' => 'set budget', 'name' => 'income',],
            ['number' => '2', 'param' => 'set budget', 'name' => 'expense',],
            ['number' => '1', 'param' => 'standard', 'name' => 'document reference',],
            ['number' => '2', 'param' => 'standard', 'name' => 'tax object',],
            ['number' => '3', 'param' => 'standard', 'name' => 'code standard',],
            ['number' => '1', 'param' => 'action', 'name' => 'check',],
            ['number' => '2', 'param' => 'action', 'name' => 'accept',],
            ['number' => '3', 'param' => 'action', 'name' => 'accept+',],
            ['number' => '4', 'param' => 'action', 'name' => 'revise',],
            ['number' => '5', 'param' => 'action', 'name' => 'reject',],
            ['number' => '1', 'param' => 'divisi sdm', 'group' => 'divisi', 'name' => 'wilayah',],
            ['number' => '2', 'param' => 'divisi sdm', 'group' => 'divisi', 'name' => 'divisi',],
            ['number' => '3', 'param' => 'divisi sdm', 'group' => 'sdm', 'name' => 'jabatan',],
            ['number' => '4', 'param' => 'divisi sdm', 'group' => 'sdm', 'name' => 'golongan',],
            ['number' => '5', 'param' => 'divisi sdm', 'group' => 'sdm', 'name' => 'kategori rating',],
        ];

        foreach ($select_data as $data) {
            $this->db->table('m_select')->insert($data);
        }
    }
}
// php spark db:seed