<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SelectOption extends Seeder
{
    public function run()
    {
        $pilih_data = [
            ['nomor' => '1', 'param' => 'sistem susut', 'nama' => 'garis lurus',],
            ['nomor' => '2', 'param' => 'sistem susut', 'nama' => 'saldo turun',],
            ['nomor' => '1', 'param' => 'kategori akun', 'nama' => '1-harta',],
            ['nomor' => '2', 'param' => 'kategori akun', 'nama' => '2-kewajiban',],
            ['nomor' => '3', 'param' => 'kategori akun', 'nama' => '3-modal',],
            ['nomor' => '4', 'param' => 'kategori akun', 'nama' => '4-pendapatan',],
            ['nomor' => '5', 'param' => 'kategori akun', 'nama' => '5-hpp',],
            ['nomor' => '6', 'param' => 'kategori akun', 'nama' => '6-biaya',],
            ['nomor' => '7', 'param' => 'kategori akun', 'nama' => '7-pendapatan lain',],
            ['nomor' => '8', 'param' => 'kategori akun', 'nama' => '8-biaya lain',],
            ['nomor' => '1', 'param' => 'golongan darah', 'nama' => 'A',],
            ['nomor' => '2', 'param' => 'golongan darah', 'nama' => 'B',],
            ['nomor' => '3', 'param' => 'golongan darah', 'nama' => 'AB',],
            ['nomor' => '4', 'param' => 'golongan darah', 'nama' => 'O',],
            ['nomor' => '1', 'param' => 'ijasah', 'nama' => 'SD',],
            ['nomor' => '2', 'param' => 'ijasah', 'nama' => 'SMP',],
            ['nomor' => '3', 'param' => 'ijasah', 'nama' => 'SMU',],
            ['nomor' => '4', 'param' => 'ijasah', 'nama' => 'D3',],
            ['nomor' => '5', 'param' => 'ijasah', 'nama' => 'S1',],
            ['nomor' => '6', 'param' => 'ijasah', 'nama' => 'S2',],
            ['nomor' => '1', 'param' => 'status ijasah', 'nama' => 'tahan',],
            ['nomor' => '2', 'param' => 'status ijasah', 'nama' => 'kembali',],
            ['nomor' => '1', 'param' => 'status pegawai', 'nama' => 'PKWT',],
            ['nomor' => '2', 'param' => 'status pegawai', 'nama' => 'PKWTT',],
            ['nomor' => '3', 'param' => 'status pegawai', 'nama' => 'PHL',],
            ['nomor' => '1', 'param' => 'mode keluar', 'nama' => 'undur diri',],
            ['nomor' => '2', 'param' => 'mode keluar', 'nama' => 'phk',],
            ['nomor' => '3', 'param' => 'mode keluar', 'nama' => 'pecat',],
            ['nomor' => '4', 'param' => 'mode keluar', 'nama' => 'pensiun',],
            ['nomor' => '1', 'param' => 'beban', 'nama' => 'proyek',],
            ['nomor' => '2', 'param' => 'beban', 'nama' => 'cabang',],
            ['nomor' => '3', 'param' => 'beban', 'nama' => 'alat tool',],
            ['nomor' => '4', 'param' => 'beban', 'nama' => 'tanah bangunan',],
            ['nomor' => '1', 'param' => 'itemso', 'nama' => 'item',],
            ['nomor' => '2', 'param' => 'itemso', 'nama' => 'alat tool',],
            ['nomor' => '3', 'param' => 'itemso', 'nama' => 'tanah bangunan',],
            ['nomor' => '4', 'param' => 'itemso', 'nama' => 'inventaris',],
            ['nomor' => '1', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'minta barang',],
            ['nomor' => '2', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'ambil barang',],
            ['nomor' => '3', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'keluar gudang',],
            ['nomor' => '4', 'param' => 'formulir', 'kelompok' => 'pembelian', 'nama' => 'pesan barang',],
            ['nomor' => '5', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kas langsung',],
            ['nomor' => '6', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kas taklangsung',],
            ['nomor' => '7', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'uang muka',],
            ['nomor' => '8', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'uang jalan',],
            ['nomor' => '9', 'param' => 'formulir', 'kelompok' => 'kas', 'nama' => 'kas pindah',],
            ['nomor' => '10', 'param' => 'formulir', 'kelompok' => 'penjualan', 'nama' => 'pesan jual',],
            ['nomor' => '11', 'param' => 'formulir', 'kelompok' => 'penjualan', 'nama' => 'pesan sewa',],
            ['nomor' => '12', 'param' => 'formulir', 'kelompok' => 'cuti', 'nama' => 'cuti',],
            ['nomor' => '13', 'param' => 'formulir', 'kelompok' => 'anggaran', 'nama' => 'anggaran proyek',],
            ['nomor' => '14', 'param' => 'formulir', 'kelompok' => 'anggaran', 'nama' => 'anggaran objek',],
            ['nomor' => '1', 'param' => 'akun grup', 'kelompok' => 'aset', 'nama' => 'alat tool',],
            ['nomor' => '2', 'param' => 'akun grup', 'kelompok' => 'aset', 'nama' => 'tanah bangunan',],
            ['nomor' => '3', 'param' => 'akun grup', 'kelompok' => 'aset', 'nama' => 'inventaris',],
            ['nomor' => '4', 'param' => 'akun grup', 'kelompok' => 'stok', 'nama' => 'barang',],
            ['nomor' => '5', 'param' => 'akun grup', 'kelompok' => 'stok', 'nama' => 'bahan',],
            ['nomor' => '6', 'param' => 'akun grup', 'kelompok' => 'penerima', 'nama' => 'pegawai',],
            ['nomor' => '7', 'param' => 'akun grup', 'kelompok' => 'penerima', 'nama' => 'pelanggan',],
            ['nomor' => '8', 'param' => 'akun grup', 'kelompok' => 'penerima', 'nama' => 'suplier',],
            ['nomor' => '9', 'param' => 'akun grup', 'kelompok' => 'penerima', 'nama' => 'subkon',],
            ['nomor' => '1', 'param' => 'akun pajak', 'kelompok' => 'pajak', 'nama' => 'ppn',],
            ['nomor' => '2', 'param' => 'akun pajak', 'kelompok' => 'pajak', 'nama' => 'pph',],
            ['nomor' => '3', 'param' => 'akun pajak', 'kelompok' => 'pajak', 'nama' => 'pjlain',],
            ['nomor' => '1', 'param' => 'akun kas', 'kelompok' => 'kas', 'nama' => 'kas',],
            ['nomor' => '2', 'param' => 'akun kas', 'kelompok' => 'kas', 'nama' => 'bank',],
            ['nomor' => '1', 'param' => 'sim', 'kelompok' => 'SIM A', 'nama' => 'SIM A',],
            ['nomor' => '2', 'param' => 'sim', 'kelompok' => 'SIM A', 'nama' => 'SIM A Umum',],
            ['nomor' => '3', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BI',],
            ['nomor' => '4', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BI Umum',],
            ['nomor' => '5', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BII',],
            ['nomor' => '6', 'param' => 'sim', 'kelompok' => 'SIM B', 'nama' => 'SIM BII Umum',],
            ['nomor' => '7', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM C',],
            ['nomor' => '8', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM CI Umum',],
            ['nomor' => '9', 'param' => 'sim', 'kelompok' => 'SIM C', 'nama' => 'SIM CII',],
            ['nomor' => '10', 'param' => 'sim', 'kelompok' => 'SIM D', 'nama' => 'SIM D',],
            ['nomor' => '11', 'param' => 'sim', 'kelompok' => 'SIM D', 'nama' => 'SIM DI',],
            ['nomor' => '1', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/0',],
            ['nomor' => '2', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/1',],
            ['nomor' => '3', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/2',],
            ['nomor' => '4', 'param' => 'ptkp', 'kelompok' => 'TK', 'nama' => 'TK/3',],
            ['nomor' => '5', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/0',],
            ['nomor' => '6', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/1',],
            ['nomor' => '7', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/2',],
            ['nomor' => '8', 'param' => 'ptkp', 'kelompok' => 'K', 'nama' => 'K/3',],
            ['nomor' => '9', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/0',],
            ['nomor' => '10', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/1',],
            ['nomor' => '11', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/2',],
            ['nomor' => '12', 'param' => 'ptkp', 'kelompok' => 'K/I', 'nama' => 'K/I/3',],
            ['nomor' => '1', 'param' => 'konfigurasi', 'nama' => 'jlsetuju',],
            ['nomor' => '2', 'param' => 'konfigurasi', 'nama' => 'cariharga',],
            ['nomor' => '1', 'param' => 'kelin', 'nama' => 'industri',],
            ['nomor' => '2', 'param' => 'kelin', 'nama' => 'non industri',],
            ['nomor' => '3', 'param' => 'kelin', 'nama' => 'subkon',],
            ['nomor' => '1', 'param' => 'trip', 'nama' => 'bbm',],
            ['nomor' => '2', 'param' => 'trip', 'nama' => 'honor',],
            ['nomor' => '3', 'param' => 'trip', 'nama' => 'byantri',],
            ['nomor' => '4', 'param' => 'trip', 'nama' => 'lembur biasa',],
            ['nomor' => '5', 'param' => 'trip', 'nama' => 'lembur besar',],
            ['nomor' => '6', 'param' => 'trip', 'nama' => 'uang makan',],
            ['nomor' => '1', 'param' => 'bentuk', 'nama' => 'alat berat',],
            ['nomor' => '2', 'param' => 'bentuk', 'nama' => 'alat industri',],
            ['nomor' => '3', 'param' => 'bentuk', 'nama' => 'truk',],
            ['nomor' => '4', 'param' => 'bentuk', 'nama' => 'mobil',],
            ['nomor' => '1', 'param' => 'setanggaran', 'nama' => 'pendapatan',],
            ['nomor' => '2', 'param' => 'setanggaran', 'nama' => 'pengeluaran',],
            ['nomor' => '1', 'param' => 'kbli', 'nama' => 'dokumen ref',],
            ['nomor' => '2', 'param' => 'kbli', 'nama' => 'objek pajak',],
            ['nomor' => '3', 'param' => 'kbli', 'nama' => 'kode baku',],
            ['nomor' => '1', 'param' => 'aksi', 'nama' => 'cek',],
            ['nomor' => '2', 'param' => 'aksi', 'nama' => 'terima',],
            ['nomor' => '3', 'param' => 'aksi', 'nama' => 'terima lanjut',],
            ['nomor' => '4', 'param' => 'aksi', 'nama' => 'revisi',],
            ['nomor' => '5', 'param' => 'aksi', 'nama' => 'tolak',],
            ['nomor' => '1', 'param' => 'divisi sdm', 'kelompok' => 'divisi', 'nama' => 'wilayah',],
            ['nomor' => '2', 'param' => 'divisi sdm', 'kelompok' => 'divisi', 'nama' => 'divisi',],
            ['nomor' => '3', 'param' => 'divisi sdm', 'kelompok' => 'sdm', 'nama' => 'jabatan',],
            ['nomor' => '4', 'param' => 'divisi sdm', 'kelompok' => 'sdm', 'nama' => 'golongan',],
            ['nomor' => '5', 'param' => 'divisi sdm', 'kelompok' => 'sdm', 'nama' => 'kategori rating',],
        ];

        foreach ($pilih_data as $data) {
            $this->db->table('m_select')->insert($data);
        }
    }
}
// php spark db:seed